# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='Resource Capacity')),
                ('utilized', models.IntegerField(verbose_name='Resource Utilized')),
                ('unutilized', models.IntegerField(verbose_name='Unutilized Resource')),
                ('ongoing', models.IntegerField(verbose_name='No. Ongoing Projects')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company', verbose_name='Company Name')),
            ],
        ),
    ]
