# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_name', models.CharField(max_length=250)),
                ('projects_unique_identifier', models.CharField(default=b'<django.db.models.fields.CharField>2018-06-24 10:21:39.807000', max_length=250, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company', verbose_name='Company Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='ongoing',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='unutilized',
        ),
        migrations.AddField(
            model_name='clients',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Projects', verbose_name='Project Name'),
        ),
    ]
