# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180624_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projects_unique_identifier',
            field=models.CharField(default=b'5312018-06-24 11:46:18.850000', max_length=250, unique=True),
        ),
    ]
