# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180624_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projects_unique_identifier',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
