# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180625_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='projects_unique_identifier',
        ),
    ]
