# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_projects_projects_unique_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['project']},
        ),
    ]
