# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180628_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='isCompleted',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
