# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_projects_iscompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_mail',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company Mail'),
        ),
    ]
