# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20180901_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadsupLive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='ETA')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='ETD')),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand/Project')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Additional Information')),
                ('isLive', models.BooleanField(default=False, verbose_name='Live')),
            ],
        ),
        migrations.RemoveField(
            model_name='clients',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='cName',
        ),
        migrations.AddField(
            model_name='projectcounter',
            name='headsup_model',
            field=models.IntegerField(blank=True, null=True, verbose_name='Heads Up'),
        ),
        migrations.AddField(
            model_name='projects',
            name='budgethours',
            field=models.IntegerField(default=True, verbose_name='Budget Hours'),
        ),
        migrations.AddField(
            model_name='projects',
            name='eTalents',
            field=models.IntegerField(default=True, verbose_name='Talent Used'),
        ),
        migrations.AddField(
            model_name='projects',
            name='estimatedHours',
            field=models.IntegerField(default=True, verbose_name='Estimated Hours'),
        ),
        migrations.AddField(
            model_name='projects',
            name='pDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='initiation date'),
        ),
        migrations.AddField(
            model_name='projects',
            name='runningHours',
            field=models.IntegerField(default=True, verbose_name='Running Hours'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_mail',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='projectcounter',
            name='adiva_incurred_hours',
            field=models.IntegerField(verbose_name='Incurred Hours'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company', verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projects_name',
            field=models.CharField(default='Enter Project Name', max_length=250, verbose_name=' Brand Name'),
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
