# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20180912_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcounter',
            name='adiva_incurred_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Incurred Hours'),
        ),
        migrations.AlterField(
            model_name='projectcounter',
            name='completed_project_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Completed Porject Number'),
        ),
        migrations.AlterField(
            model_name='projectcounter',
            name='feedback_received_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Feedback Received Number'),
        ),
        migrations.AlterField(
            model_name='projectcounter',
            name='total_phases_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Phase Number'),
        ),
    ]
