# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180916_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='headsuplive',
            name='scope_of_work',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Scope of Work'),
        ),
    ]
