# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_headsuplive_scope_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headsuplive',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='ETD'),
        ),
        migrations.AlterField(
            model_name='headsuplive',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='ETA'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='pDate',
            field=models.DateField(blank=True, null=True, verbose_name='initiation date'),
        ),
    ]
