# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20180929_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='updatedTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
