# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fourqater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('project_completed_jan', models.IntegerField(null=True)),
                ('total_phase_jan', models.IntegerField(null=True)),
                ('feedback_received_jan', models.IntegerField(null=True)),
                ('adiva_incurred_hours_jan', models.IntegerField(null=True)),
                ('project_completed_feb', models.IntegerField(null=True)),
                ('total_phase_feb', models.IntegerField(null=True)),
                ('feedback_received_feb', models.IntegerField(null=True)),
                ('adiva_incurred_hours_feb', models.IntegerField(null=True)),
                ('project_completed_mar', models.IntegerField(null=True)),
                ('total_phase_mar', models.IntegerField(null=True)),
                ('feedback_received_mar', models.IntegerField(null=True)),
                ('adiva_incurred_hours_mar', models.IntegerField(null=True)),
                ('project_completed_apr', models.IntegerField(null=True)),
                ('total_phase_apr', models.IntegerField(null=True)),
                ('feedback_received_apr', models.IntegerField(null=True)),
                ('adiva_incurred_hours_apr', models.IntegerField(null=True)),
                ('project_completed_may', models.IntegerField(null=True)),
                ('total_phase_may', models.IntegerField(null=True)),
                ('feedback_received_may', models.IntegerField(null=True)),
                ('adiva_incurred_hours_may', models.IntegerField(null=True)),
                ('project_completed_jun', models.IntegerField(null=True)),
                ('total_phase_jun', models.IntegerField(null=True)),
                ('feedback_received_jun', models.IntegerField(null=True)),
                ('adiva_incurred_hours_jun', models.IntegerField(null=True)),
                ('project_completed_jul', models.IntegerField(null=True)),
                ('total_phase_jul', models.IntegerField(null=True)),
                ('feedback_received_jul', models.IntegerField(null=True)),
                ('adiva_incurred_hours_jul', models.IntegerField(null=True)),
                ('project_completed_aug', models.IntegerField(null=True)),
                ('total_phase_aug', models.IntegerField(null=True)),
                ('feedback_received_aug', models.IntegerField(null=True)),
                ('adiva_incurred_hours_aug', models.IntegerField(null=True)),
                ('project_completed_sep', models.IntegerField(null=True)),
                ('total_phase_sep', models.IntegerField(null=True)),
                ('feedback_received_sep', models.IntegerField(null=True)),
                ('adiva_incurred_hours_sep', models.IntegerField(null=True)),
                ('project_completed_oct', models.IntegerField(null=True)),
                ('total_phase_oct', models.IntegerField()),
                ('feedback_received_oct', models.IntegerField(null=True)),
                ('adiva_incurred_hours_oct', models.IntegerField(null=True)),
                ('project_completed_nov', models.IntegerField(null=True)),
                ('total_phase_nov', models.IntegerField(null=True)),
                ('feedback_received_nov', models.IntegerField(null=True)),
                ('adiva_incurred_hours_nov', models.IntegerField(null=True)),
                ('project_completed_dec', models.IntegerField(null=True)),
                ('total_phase_dec', models.IntegerField()),
                ('feedback_received_dec', models.IntegerField(null=True)),
                ('adiva_incurred_hours_dec', models.IntegerField(null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ongoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_project', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=250)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources_capacity', models.IntegerField(null=True)),
                ('resources_utilized', models.IntegerField(null=True)),
                ('ongoing_projects', models.IntegerField(null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
