# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='unutilized_resource',
            field=models.IntegerField(null=True),
        ),
    ]
