# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_resources_unutilized_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='unutilized_resource',
        ),
    ]
