# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180530_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(),
        ),
    ]
