# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180530_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcounter',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Months', verbose_name='Mont'),
        ),
        migrations.AlterField(
            model_name='projectcounter',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Year', verbose_name='Year'),
        ),
    ]
