# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180530_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcounter',
            name='adiva_incurred_hours',
            field=models.IntegerField(default=0, verbose_name='Adiva Incurred Hours'),
        ),
        migrations.AlterField(
            model_name='projectcounter',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Months', verbose_name='Month'),
        ),
    ]
