# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180603_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_project_number', models.IntegerField(verbose_name='Completed Porject Number')),
                ('total_phases_number', models.IntegerField(verbose_name='Total Phase Number')),
                ('feedback_received_number', models.IntegerField(verbose_name='Feedback Received Number')),
                ('adiva_incurred_hours', models.IntegerField(verbose_name='Adiva Incurred Hours')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company', verbose_name='Company Name')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Months', verbose_name='Month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Year', verbose_name='Year')),
            ],
        ),
    ]
